### ISSUE TITLE
Pyaudio/portaudio package mismatch on Windows x64

### ISSUE THREAD

**Issue by aleneum** [conda-forge/pyaudio-feedstock#4]
Issue:

When trying to install pyaudio on Windows with conda-forge, conda will use `pyaudio` from `pkgs/main` and `portaudio` from `conda-forge`:

```
$ conda install -c conda-forge -d pyaudio
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Miniconda3-x64\envs\test-environment

  added / updated specs:
    - pyaudio


The following NEW packages will be INSTALLED:

  portaudio          conda-forge/win-64::portaudio-19.6.0-h6538335_2
  pyaudio            pkgs/main/win-64::pyaudio-0.2.11-py37hfa6e2cd_1
```

Importing pyaudio will cause an import error ([ref](https://ci.appveyor.com/project/aleneum/pya/builds/26539151#L216))

```
>>> import pyaudio
...
# trying C:\Miniconda3-x64\envs\test-environment\lib\site-packages\_portaudio.cp37-win_amd64.pyd
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3-x64\envs\test-environment\lib\site-packages\pyaudio.py", line 116, in <module>
    import _portaudio as pa
ImportError: DLL load failed: The specified module could not be found.
```
I assume that mixing `conda-forge/win-64::portaudio` and `pkgs/main/win-64::pyaudio` does not work.
This seems to be an issue for Windows only. Using Linux will result in both (`portaudio` and `pyaudio`) packages being retrieved from `conda-forge` ([ref](https://travis-ci.org/aleneum/pya/jobs/570768223#L535)) while in case of MacOS `pkgs/main` ([ref](https://travis-ci.org/aleneum/pya/jobs/570768237#L393)) will be used.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
packages in environment at C:\Miniconda3-x64\envs\test-environment:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.2.2                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test-environment
    active env location : C:\Miniconda3-x64\envs\test-environment
            shell level : 1
       user config file : C:\Users\alneuman\.condarc
 populated config files : C:\Users\alneuman\.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.1.final.0
       virtual packages : __cuda=9.1
       base environment : C:\Miniconda3-x64  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3-x64\pkgs
                          C:\Users\alneuman\.conda\pkgs
                          C:\Users\alneuman\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3-x64\envs
                          C:\Users\alneuman\.conda\envs
                          C:\Users\alneuman\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment]
`conda-forge` does not have a `pyaudio` package on Windows.
See https://github.com/conda-forge/pyaudio-feedstock/blob/master/recipe/meta.yaml#L17

PRs to fix that are welcomed!

**Comment by Hassanzadeh-sd** [comment]
First run your IDE or CMD as Administrator and run the following:

```
    pip install pipwin
    pipwin install pyaudio
```

**Comment by jdelange** [comment]
On `pip install pipwin` I get

> ERROR: Could not find a version that satisfies the requirement piwin (from versions: none)
> ERROR: No matching distribution found for piwin

**Comment by banji007** [comment]
Even for me - this worked on Windows
pip install pipwin
pipwin install pyaudio

**Comment by kalyaniakant** [comment]
White doing  import pyaudio as pa,
Getting error File "C:\Users\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyaudio.py", line 116, in <module>
    import _portaudio as pa

ModuleNotFoundError: No module named '_portaudio'
